// Sprint 604A — DONNA Director Coverage Registry
// Pure TypeScript — no DB calls, no AI calls, no mutations, no side effects.
// Source of truth for programmatic access to DONNA connectivity status across director routes.
// Derived from DONNA_DIRECTOR_CONNECTIVITY_AUDIT.md.

export type DonnaTier =
  | 'fully_connected'
  | 'well_connected'
  | 'partially_connected'
  | 'weak'
  | 'not_connected'

export type FixPriority = 'P0' | 'P1' | 'P2' | 'none'

export interface DonnaRouteCoverage {
  route: string
  label: string
  primaryJob: string
  score: number
  tier: DonnaTier
  hasPresence: boolean
  isPageAware: boolean
  isObjectAware: boolean
  canExplain: boolean
  canSummarize: boolean
  canRecommend: boolean
  canDraft: boolean
  canRoute: boolean
  canApply: boolean
  approvalRequired: boolean | null
  parentPlayerRisk: boolean
  fixPriority: FixPriority
  missingContext: string[]
  missingActions: string[]
}

export const DIRECTOR_DONNA_COVERAGE_REGISTRY: DonnaRouteCoverage[] = [
  {
    route: '/director/review',
    label: 'Review Queue',
    primaryJob: 'Director approves or rejects all DONNA-drafted items before they take effect',
    score: 9,
    tier: 'fully_connected',
    hasPresence: true,
    isPageAware: true,
    isObjectAware: true,
    canExplain: true,
    canSummarize: true,
    canRecommend: true,
    canDraft: true,
    canRoute: true,
    canApply: true,
    approvalRequired: true,
    parentPlayerRisk: false,
    fixPriority: 'none',
    missingContext: ['DONNA follow-up Q&A on draft items'],
    missingActions: ['Inline DONNA rationale Q&A', 'Bulk-approve with DONNA reasoning summary'],
  },
  {
    route: '/director/onboarding/interview',
    label: 'Director Interview',
    primaryJob: 'DONNA-guided director interview to capture academy philosophy and preferences',
    score: 9,
    tier: 'fully_connected',
    hasPresence: true,
    isPageAware: true,
    isObjectAware: true,
    canExplain: true,
    canSummarize: true,
    canRecommend: true,
    canDraft: true,
    canRoute: true,
    canApply: true,
    approvalRequired: true,
    parentPlayerRisk: false,
    fixPriority: 'none',
    missingContext: [],
    missingActions: [],
  },
  {
    route: '/director/donna',
    label: 'DONNA Hub',
    primaryJob: 'Director DONNA command center — attention queue, risks, recommended actions, chat shell',
    score: 8,
    tier: 'fully_connected',
    hasPresence: true,
    isPageAware: true,
    isObjectAware: false,
    canExplain: true,
    canSummarize: true,
    canRecommend: true,
    canDraft: false,
    canRoute: true,
    canApply: false,
    approvalRequired: null,
    parentPlayerRisk: false,
    fixPriority: 'none',
    missingContext: ['Selected player/session object', 'Curriculum coverage state'],
    missingActions: ['Inline approve from DONNA hub'],
  },
  {
    route: '/director/review/[actionId]',
    label: 'Review Item Detail',
    primaryJob: 'Per-item review with full context panel',
    score: 8,
    tier: 'fully_connected',
    hasPresence: true,
    isPageAware: true,
    isObjectAware: true,
    canExplain: true,
    canSummarize: true,
    canRecommend: false,
    canDraft: false,
    canRoute: false,
    canApply: true,
    approvalRequired: true,
    parentPlayerRisk: false,
    fixPriority: 'P2',
    missingContext: ['DONNA follow-up Q&A', 'Related items cross-reference'],
    missingActions: ['Inline DONNA Q&A on the item'],
  },
  {
    route: '/director/command-center',
    label: 'Command Center',
    primaryJob: 'Voice/text command intake; command history; structured draft creation',
    score: 7,
    tier: 'well_connected',
    hasPresence: true,
    isPageAware: true,
    isObjectAware: false,
    canExplain: false,
    canSummarize: true,
    canRecommend: false,
    canDraft: true,
    canRoute: true,
    canApply: false,
    approvalRequired: true,
    parentPlayerRisk: false,
    fixPriority: 'P2',
    missingContext: ['Free-form NLU', 'Multi-turn context', 'Player name disambiguation'],
    missingActions: ['AI inference layer', 'Disambiguation flow'],
  },
  {
    route: '/director/today',
    label: "Today's Academy",
    primaryJob: "Today's sessions, player attention risk, command brief, DONNA suggestion chips",
    score: 7,
    tier: 'well_connected',
    hasPresence: true,
    isPageAware: true,
    isObjectAware: false,
    canExplain: false,
    canSummarize: true,
    canRecommend: true,
    canDraft: false,
    canRoute: false,
    canApply: false,
    approvalRequired: null,
    parentPlayerRisk: false,
    fixPriority: 'none',
    missingContext: ['Per-session drill-down', 'Per-player drill-down from today view'],
    missingActions: ['Draft action from today page'],
  },
  {
    route: '/director/players/[playerId]',
    label: 'Player Profile',
    primaryJob: 'Full player intelligence hub — curriculum, assessment, priorities, gate evidence, coach notes, parent guidance',
    score: 7,
    tier: 'well_connected',
    hasPresence: true,
    isPageAware: true,
    isObjectAware: true,
    canExplain: false,
    canSummarize: false,
    canRecommend: true,
    canDraft: true,
    canRoute: true,
    canApply: false,
    approvalRequired: true,
    parentPlayerRisk: false,
    fixPriority: 'P1',
    missingContext: ['Inline DONNA Q&A chat shell', 'DONNA explanation of blocked gates'],
    missingActions: ['DONNA inline Q&A chip', '"What should I do for this player today?" response'],
  },
  {
    route: '/director/curriculum',
    label: 'Curriculum Explorer',
    primaryJob: 'View and manage the full curriculum structure, levels, drills, health status',
    score: 6,
    tier: 'well_connected',
    hasPresence: false,
    isPageAware: true,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: true,
    canRoute: true,
    canApply: false,
    approvalRequired: true,
    parentPlayerRisk: false,
    fixPriority: 'P2',
    missingContext: ['Which level is currently expanded', 'Requirement detail in DONNA context', 'Coverage gaps for the selected level'],
    missingActions: ['"DONNA, what is weak in this level?" chip', 'Per-drill DONNA context'],
  },
  {
    route: '/director/sessions/[sessionId]',
    label: 'Session Detail',
    primaryJob: 'View session plan, attendance, wrap-up, coach notes; generate adjustments',
    score: 6,
    tier: 'well_connected',
    hasPresence: false,
    isPageAware: true,
    isObjectAware: true,
    canExplain: false,
    canSummarize: false,
    canRecommend: true,
    canDraft: true,
    canRoute: true,
    canApply: false,
    approvalRequired: true,
    parentPlayerRisk: false,
    fixPriority: 'P2',
    missingContext: ["Session's curriculum context", 'Planned vs. actual DONNA narrative'],
    missingActions: ['Inline DONNA Q&A about session flags'],
  },
  {
    route: '/director/templates/class/[templateId]',
    label: 'Class Template Builder',
    primaryJob: 'Build class templates with curriculum blocks, drills, and lesson plans',
    score: 6,
    tier: 'well_connected',
    hasPresence: false,
    isPageAware: true,
    isObjectAware: true,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: true,
    canRoute: false,
    canApply: true,
    approvalRequired: false,
    parentPlayerRisk: false,
    fixPriority: 'P1',
    missingContext: [],
    missingActions: ['Lesson plan apply should always pass through review queue'],
  },
  {
    route: '/director/fitness/templates/[templateId]',
    label: 'Fitness Template Builder',
    primaryJob: 'Build fitness templates with exercise blocks',
    score: 5,
    tier: 'partially_connected',
    hasPresence: false,
    isPageAware: true,
    isObjectAware: true,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: true,
    canRoute: false,
    canApply: true,
    approvalRequired: false,
    parentPlayerRisk: false,
    fixPriority: 'P1',
    missingContext: [],
    missingActions: ['Review gate on session generation (bypasses proposed_actions pipeline)'],
  },
  {
    route: '/director',
    label: 'Main Dashboard',
    primaryJob: 'Academy overview — KPI cards, priority queue, player alerts, session list, DONNA executive card',
    score: 4,
    tier: 'partially_connected',
    hasPresence: false,
    isPageAware: false,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: false,
    canRoute: false,
    canApply: false,
    approvalRequired: null,
    parentPlayerRisk: false,
    fixPriority: 'P1',
    missingContext: ['DONNA does not know which KPI the director is viewing', 'No explanation of what each signal means'],
    missingActions: ['KPI explainer chip', '"What should I do first?" DONNA chip'],
  },
  {
    route: '/director/templates',
    label: 'Templates Hub',
    primaryJob: 'Navigate to class template and fitness template libraries; DONNA template suggestions',
    score: 4,
    tier: 'partially_connected',
    hasPresence: false,
    isPageAware: true,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: true,
    canDraft: false,
    canRoute: false,
    canApply: false,
    approvalRequired: null,
    parentPlayerRisk: false,
    fixPriority: 'none',
    missingContext: [],
    missingActions: [],
  },
  {
    route: '/director/level-up',
    label: 'Level Advancement Pipeline',
    primaryJob: 'View players ready or overdue for advancement; trigger level movement draft with DONNA',
    score: 5,
    tier: 'partially_connected',
    hasPresence: true,
    isPageAware: true,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: true,
    canRoute: true,
    canApply: false,
    approvalRequired: true,
    parentPlayerRisk: false,
    fixPriority: 'P1',
    missingContext: ['Per-player DONNA context object (level names auto-filled)', 'Why a specific player is overdue (drill-down narrative)'],
    missingActions: ['Apply path: DonnaLevelMovementApplyControls not yet wired to review queue DonnaDraftCard'],
  },
  {
    route: '/director/placement',
    label: 'Placement Engine',
    primaryJob: 'Place new/pending players into groups and curriculum levels',
    score: 2,
    tier: 'weak',
    hasPresence: false,
    isPageAware: false,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: false,
    canRoute: false,
    canApply: false,
    approvalRequired: true,
    parentPlayerRisk: false,
    fixPriority: 'P0',
    missingContext: ['DONNA cannot suggest level/group from assessment answers'],
    missingActions: ['Expose placementDraftAction.ts via DONNA placement suggestion button'],
  },
  {
    route: '/director/curriculum/builder',
    label: 'Curriculum Builder',
    primaryJob: 'Setup builder for creating curriculum from scratch or from the starter template',
    score: 1,
    tier: 'not_connected',
    hasPresence: false,
    isPageAware: false,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: false,
    canRoute: false,
    canApply: false,
    approvalRequired: null,
    parentPlayerRisk: false,
    fixPriority: 'P1',
    missingContext: ['All — DONNA has zero visibility into the builder flow'],
    missingActions: ['DONNA step-by-step guidance', '"What should this level include?" prompts'],
  },
  {
    route: '/director/curriculum/learning',
    label: 'Learning Modules',
    primaryJob: 'Director preview of in-memory learning module content by level and domain',
    score: 1,
    tier: 'not_connected',
    hasPresence: false,
    isPageAware: false,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: false,
    canRoute: false,
    canApply: false,
    approvalRequired: null,
    parentPlayerRisk: false,
    fixPriority: 'none',
    missingContext: [],
    missingActions: [],
  },
  {
    route: '/director/players',
    label: 'Players Directory',
    primaryJob: 'Search and browse all active players; navigate to individual profiles',
    score: 1,
    tier: 'not_connected',
    hasPresence: false,
    isPageAware: false,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: false,
    canRoute: false,
    canApply: false,
    approvalRequired: null,
    parentPlayerRisk: false,
    fixPriority: 'P0',
    missingContext: ['DONNA cannot answer "show me players at risk"'],
    missingActions: ['DONNA roster intelligence chip', '"Who should I focus on today?" answer'],
  },
  {
    route: '/director/sessions',
    label: 'Sessions List',
    primaryJob: 'Browse all sessions; navigate to individual session detail',
    score: 1,
    tier: 'not_connected',
    hasPresence: false,
    isPageAware: false,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: false,
    canRoute: false,
    canApply: false,
    approvalRequired: null,
    parentPlayerRisk: false,
    fixPriority: 'P2',
    missingContext: ['DONNA cannot surface sessions with missing wrap-ups'],
    missingActions: ['DONNA sessions intelligence chip'],
  },
  {
    route: '/director/kpi',
    label: 'KPI Dashboard',
    primaryJob: 'Academy KPI breakdown — attendance rates, development velocity',
    score: 1,
    tier: 'not_connected',
    hasPresence: false,
    isPageAware: false,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: false,
    canRoute: false,
    canApply: false,
    approvalRequired: null,
    parentPlayerRisk: false,
    fixPriority: 'P0',
    missingContext: ['kpiExplainer.ts exists but is not wired'],
    missingActions: ['KPI explainer chip', '"What is driving this KPI?" DONNA response'],
  },
  {
    route: '/director/signals',
    label: 'Development Signals',
    primaryJob: 'Surface attendance concerns, wrap-up signals, lesson signals across the academy',
    score: 1,
    tier: 'not_connected',
    hasPresence: false,
    isPageAware: false,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: false,
    canRoute: false,
    canApply: false,
    approvalRequired: null,
    parentPlayerRisk: false,
    fixPriority: 'P1',
    missingContext: ['DONNA cannot narrate what signals mean or recommend action'],
    missingActions: ['DONNA signal narrator panel'],
  },
  {
    route: '/director/coaches',
    label: 'Coaches Directory',
    primaryJob: 'Browse coaches and their assignments',
    score: 1,
    tier: 'not_connected',
    hasPresence: false,
    isPageAware: false,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: false,
    canRoute: false,
    canApply: false,
    approvalRequired: null,
    parentPlayerRisk: false,
    fixPriority: 'none',
    missingContext: [],
    missingActions: [],
  },
  {
    route: '/director/coaches/[coachId]',
    label: 'Coach Profile',
    primaryJob: "View coach assignment, session history, and wrap-up compliance",
    score: 1,
    tier: 'not_connected',
    hasPresence: false,
    isPageAware: false,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: false,
    canRoute: false,
    canApply: false,
    approvalRequired: null,
    parentPlayerRisk: false,
    fixPriority: 'P1',
    missingContext: ['donnaCoachIntelligenceAction.ts exists but not wired'],
    missingActions: ['DonnaCoachIntelligencePanel'],
  },
  {
    route: '/director/parents',
    label: 'Parents List',
    primaryJob: 'Browse parent/guardian accounts and linking status',
    score: 1,
    tier: 'not_connected',
    hasPresence: false,
    isPageAware: false,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: false,
    canRoute: false,
    canApply: false,
    approvalRequired: null,
    parentPlayerRisk: false,
    fixPriority: 'none',
    missingContext: [],
    missingActions: [],
  },
  {
    route: '/director/settings',
    label: 'Academy Settings',
    primaryJob: 'Update academy name, preferences',
    score: 1,
    tier: 'not_connected',
    hasPresence: false,
    isPageAware: false,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: false,
    canRoute: false,
    canApply: false,
    approvalRequired: null,
    parentPlayerRisk: false,
    fixPriority: 'none',
    missingContext: [],
    missingActions: [],
  },
  {
    route: '/director/pilot-readiness',
    label: 'Pilot Readiness Dashboard',
    primaryJob: '30-item pilot launch checklist',
    score: 1,
    tier: 'not_connected',
    hasPresence: false,
    isPageAware: false,
    isObjectAware: false,
    canExplain: false,
    canSummarize: false,
    canRecommend: false,
    canDraft: false,
    canRoute: false,
    canApply: false,
    approvalRequired: null,
    parentPlayerRisk: false,
    fixPriority: 'none',
    missingContext: [],
    missingActions: [],
  },
]

export function getRoutesByTier(tier: DonnaTier): DonnaRouteCoverage[] {
  return DIRECTOR_DONNA_COVERAGE_REGISTRY.filter(r => r.tier === tier)
}

export function getRoutesByPriority(priority: FixPriority): DonnaRouteCoverage[] {
  return DIRECTOR_DONNA_COVERAGE_REGISTRY.filter(r => r.fixPriority === priority)
}

export function getAverageScore(): number {
  const total = DIRECTOR_DONNA_COVERAGE_REGISTRY.reduce((sum, r) => sum + r.score, 0)
  return Math.round((total / DIRECTOR_DONNA_COVERAGE_REGISTRY.length) * 10) / 10
}

export function getRoutesWithApprovalGap(): DonnaRouteCoverage[] {
  return DIRECTOR_DONNA_COVERAGE_REGISTRY.filter(
    r => r.canApply && r.approvalRequired === false,
  )
}

export function getRoutesWithNoPresence(): DonnaRouteCoverage[] {
  return DIRECTOR_DONNA_COVERAGE_REGISTRY.filter(r => !r.hasPresence)
}
