// Sprint 606 — Director DONNA Universal Action Registry V1
// Authoritative registry of every DONNA action available to directors in AcademyOS.
// Pure TypeScript — no DB calls, no AI calls, no mutations, no side effects.
// Complements donnaActionTypes.ts (Sprint 1020) — director scope only, not a replacement.
// Utility functions for lookup by id, route, domain, class.

import type {
  DirectorDonnaAction,
  DirectorActionDomain,
  DirectorActionClass,
} from './directorActionTypes'

// Re-export types so consumers can import from one location.
export type { DirectorDonnaAction, DirectorActionDomain, DirectorActionClass }

// ── Registry ──────────────────────────────────────────────────────────────────

export const DIRECTOR_DONNA_ACTIONS: DirectorDonnaAction[] = [

  // ── answer_only ───────────────────────────────────────────────────────────
  // DONNA explains or summarizes. No state change. No draft. No approval gate.

  {
    id: 'explain_director_dashboard',
    displayName: 'Explain the director dashboard',
    naturalLanguageExamples: [
      'What should I do first?',
      'What does this dashboard show?',
      'What is the most important thing right now?',
      'What should I be paying attention to today?',
    ],
    domain: 'director_dashboard',
    actionClass: 'answer_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['AcademyContext'],
    requiredObjectIds: [],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'partially_implemented',
    uiWiringStatus: 'partial',
    routes: ['/director', '/director/donna'],
    safetyNotes: ['Read-only. No state changes.'],
    missingDependencies: ['DonnaFirstActionChip component on /director'],
  },

  {
    id: 'explain_kpi',
    displayName: 'Explain what a KPI means',
    naturalLanguageExamples: [
      'Why is attendance red?',
      'What does this KPI mean?',
      'Why is this metric low?',
      'What is driving the drop in development velocity?',
    ],
    domain: 'kpi_reporting',
    actionClass: 'answer_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['KpiContext'],
    requiredObjectIds: [],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'implemented_not_wired',
    uiWiringStatus: 'not_wired',
    routes: ['/director/kpi', '/director'],
    safetyNotes: ['kpiExplainer.ts exists in src/lib/donna/kpiExplanations/ — not yet wired to KPI page.'],
    missingDependencies: ['DonnaKpiExplainerChip component', 'Wire /director/kpi page to DONNA'],
  },

  {
    id: 'summarize_kpi',
    displayName: 'Summarize KPI trends for the academy',
    naturalLanguageExamples: [
      'Summarize this week\'s KPIs',
      'How are we tracking overall?',
      'Give me the KPI snapshot for the academy',
    ],
    domain: 'kpi_reporting',
    actionClass: 'answer_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['AcademyContext', 'KpiContext'],
    requiredObjectIds: [],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'implemented_not_wired',
    uiWiringStatus: 'not_wired',
    routes: ['/director/kpi', '/director/donna'],
    safetyNotes: ['groupKpiSummaryAction.ts exists — not connected to /director/kpi page.'],
    missingDependencies: ['DonnaKpiSummaryPanel on /director/kpi'],
  },

  {
    id: 'identify_curriculum_gaps',
    displayName: 'Identify curriculum coverage gaps',
    naturalLanguageExamples: [
      'What is missing in the curriculum?',
      'Which levels have coverage gaps?',
      'What are the biggest holes in Orange 2?',
      'Which skills are under-covered?',
    ],
    domain: 'curriculum',
    actionClass: 'answer_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['CurriculumContext'],
    requiredObjectIds: [],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'implemented_not_wired',
    uiWiringStatus: 'partial',
    routes: ['/director/curriculum', '/director/donna'],
    safetyNotes: ['Curriculum coverage library exists. DONNA context not passed per selected level yet.'],
    missingDependencies: ['Level context pass-through when director expands a level on /director/curriculum'],
  },

  {
    id: 'explain_level_movement',
    displayName: 'Explain why a player is ready or overdue',
    naturalLanguageExamples: [
      'Why is this player overdue for advancement?',
      'What evidence supports moving them up?',
      'What is blocking level progression?',
      'Explain this player\'s readiness score',
    ],
    domain: 'level_movement',
    actionClass: 'answer_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['PlayerContext'],
    requiredObjectIds: ['player_id'],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'partially_implemented',
    uiWiringStatus: 'partial',
    routes: ['/director/level-up', '/director/players/[playerId]'],
    safetyNotes: ['Read-only explanation. No level change. Draws from v_reassessment_pipeline data.'],
    missingDependencies: ['Per-player PlayerContext provider on /director/level-up row expand'],
  },

  {
    id: 'summarize_player_profile',
    displayName: 'Summarize a player\'s development profile',
    naturalLanguageExamples: [
      'Give me a summary of this player',
      'What is the situation with this player?',
      'What should I know about this player today?',
      'What are the key things to address for this player?',
    ],
    domain: 'player_profiles',
    actionClass: 'answer_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['PlayerContext'],
    requiredObjectIds: ['player_id'],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'implemented_not_wired',
    uiWiringStatus: 'not_wired',
    routes: ['/director/players/[playerId]'],
    safetyNotes: ['donnaContextActions.ts player_profile type exists. Raw coach notes never exposed in output.'],
    missingDependencies: ['DonnaPlayerChatShell component on /director/players/[playerId]'],
  },

  {
    id: 'summarize_roster_gaps',
    displayName: 'Summarize roster attention priorities',
    naturalLanguageExamples: [
      'Who should I focus on today?',
      'Which players are at risk?',
      'Which groups need attention?',
      'Who is falling behind?',
    ],
    domain: 'groups_rosters',
    actionClass: 'answer_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['AcademyContext'],
    requiredObjectIds: [],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'implemented_not_wired',
    uiWiringStatus: 'not_wired',
    routes: ['/director/players', '/director/signals', '/director/donna'],
    safetyNotes: ['Uses attentionItems from loadDirectorDonnaContext — context is already available.'],
    missingDependencies: ['DonnaRosterIntelligencePanel on /director/players'],
  },

  {
    id: 'explain_licensing_health',
    displayName: 'Explain academy curriculum licensing health',
    naturalLanguageExamples: [
      'What is our licensing status?',
      'Are we at risk of any curriculum licensing issue?',
      'Explain the licensing health indicator',
    ],
    domain: 'licensing_health',
    actionClass: 'answer_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['AcademyContext'],
    requiredObjectIds: [],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'registry_only',
    uiWiringStatus: 'not_wired',
    routes: ['/director/curriculum', '/director/kpi', '/director/donna'],
    safetyNotes: ['Read-only explanation. No licensing mutations.'],
    missingDependencies: ['Licensing health backend model', 'DONNA licensing explainer action file'],
  },

  {
    id: 'explain_review_queue_item',
    displayName: 'Explain what a review queue item means',
    naturalLanguageExamples: [
      'Why did DONNA draft this?',
      'Explain this proposed action',
      'What will happen if I approve this?',
      'What is this review item about?',
    ],
    domain: 'review_queue',
    actionClass: 'answer_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['ReviewItemContext'],
    requiredObjectIds: ['proposed_action_id'],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'partially_implemented',
    uiWiringStatus: 'partial',
    routes: ['/director/review', '/director/review/[actionId]'],
    safetyNotes: ['Draft cards show static rationale. Inline interactive Q&A not yet built.'],
    missingDependencies: [
      'proposed_actions.donna_rationale DB column (migration)',
      'Inline DONNA Q&A chip on DonnaDraftCard',
    ],
  },

  {
    id: 'summarize_coach_notes',
    displayName: 'Summarize coach observations for a player',
    naturalLanguageExamples: [
      'What have coaches said about this player?',
      'Summarize recent coach observations',
      'What patterns are coaches seeing?',
    ],
    domain: 'coach_notes',
    actionClass: 'answer_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['PlayerContext'],
    requiredObjectIds: ['player_id'],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'implemented_not_wired',
    uiWiringStatus: 'not_wired',
    routes: ['/director/players/[playerId]', '/director/coaches/[coachId]'],
    safetyNotes: [
      'Director-only surface. Raw coach notes never exposed to parents or players.',
      'donnaCoachIntelligenceAction.ts exists — not wired to coach profile page.',
    ],
    missingDependencies: ['DonnaPlayerChatShell', 'DonnaCoachIntelligencePanel on /director/coaches/[coachId]'],
  },

  {
    id: 'request_clarification',
    displayName: 'Ask one clarifying question to resolve an ambiguous request',
    naturalLanguageExamples: [
      'Which player did you mean?',
      'Can you tell me a bit more about what you\'re looking for?',
      'I want to make sure I get this right — which level are you focusing on?',
    ],
    domain: 'director_dashboard',
    actionClass: 'answer_only',
    allowedRoles: ['academy_director'],
    requiredContext: [],
    requiredObjectIds: [],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'partially_implemented',
    uiWiringStatus: 'partial',
    routes: ['*'],
    safetyNotes: ['DONNA asks one clarifying question at a time — never stacks multiple questions in one response.'],
    missingDependencies: [],
  },

  {
    id: 'explain_curriculum_builder_step',
    displayName: 'Explain a curriculum builder setup step',
    naturalLanguageExamples: [
      'What am I configuring here?',
      'What should I put in this field?',
      'How should I structure this level?',
      'What does this step do?',
    ],
    domain: 'curriculum_builder',
    actionClass: 'answer_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['CurriculumContext'],
    requiredObjectIds: [],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'registry_only',
    uiWiringStatus: 'not_wired',
    routes: ['/director/curriculum/builder'],
    safetyNotes: ['Read-only guidance. DONNA never writes curriculum during builder explanation.'],
    missingDependencies: ['DONNA step guidance panel on /director/curriculum/builder'],
  },

  {
    id: 'explain_academy_setup',
    displayName: 'Explain academy setup and onboarding flow',
    naturalLanguageExamples: [
      'How do I set up the academy?',
      'What do I need to do first?',
      'Walk me through the onboarding',
      'What is the setup checklist?',
    ],
    domain: 'academy_setup',
    actionClass: 'answer_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['AcademyContext'],
    requiredObjectIds: [],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'partially_implemented',
    uiWiringStatus: 'partial',
    routes: ['/director/onboarding/interview', '/director/donna'],
    safetyNotes: ['Read-only orientation. No academy settings mutations.'],
    missingDependencies: [],
  },

  {
    id: 'explain_academy_settings',
    displayName: 'Explain an academy settings option',
    naturalLanguageExamples: [
      'What does this setting do?',
      'How do I change the academy name?',
      'What are the academy preferences?',
      'How does this preference affect players?',
    ],
    domain: 'academy_settings',
    actionClass: 'answer_only',
    allowedRoles: ['academy_director'],
    requiredContext: [],
    requiredObjectIds: [],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'registry_only',
    uiWiringStatus: 'not_wired',
    routes: ['/director/settings'],
    safetyNotes: ['Read-only explanation. DONNA does not mutate settings.'],
    missingDependencies: ['DONNA settings explainer chip on /director/settings'],
  },

  {
    id: 'summarize_template_library',
    displayName: 'Summarize available session templates',
    naturalLanguageExamples: [
      'What templates do we have?',
      'Show me what session templates exist for Orange 1',
      'Which templates are ready to use?',
      'Summarize the template library',
    ],
    domain: 'templates',
    actionClass: 'answer_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['AcademyContext'],
    requiredObjectIds: [],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'partially_implemented',
    uiWiringStatus: 'partial',
    routes: ['/director/templates', '/director/donna'],
    safetyNotes: ['Read-only. No template mutations.'],
    missingDependencies: ['DONNA template summary chip on /director/templates'],
  },

  // ── draft_only ────────────────────────────────────────────────────────────
  // DONNA creates a proposed_actions row. Director reviews in queue.
  // No state changes until director explicitly approves.

  {
    id: 'draft_attendance_exception',
    displayName: 'Draft an attendance exception',
    naturalLanguageExamples: [
      'Mark a player as absent today',
      'Record an attendance exception',
      'Flag that a player was late',
      'Note that a player left early',
    ],
    domain: 'attendance',
    actionClass: 'draft_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['SessionContext'],
    requiredObjectIds: ['session_id', 'player_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'attendance_exception',
    implementationStatus: 'implemented_and_wired',
    uiWiringStatus: 'wired',
    routes: ['/director/sessions/[sessionId]'],
    safetyNotes: [
      'Creates proposed_actions row only. No session_attendance write until approved.',
      'Director-only visibility until approved.',
    ],
    missingDependencies: [],
  },

  {
    id: 'draft_parent_summary',
    displayName: 'Draft a parent-safe development summary',
    naturalLanguageExamples: [
      'Write a parent update for this player',
      'Draft a summary to send to parents',
      'Create a parent communication for this player',
      'Prepare a parent-safe progress summary',
    ],
    domain: 'parent_summaries',
    actionClass: 'draft_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['PlayerContext'],
    requiredObjectIds: ['player_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: true,
    auditLogRequired: true,
    proposedActionType: 'parent_communication',
    implementationStatus: 'implemented_and_wired',
    uiWiringStatus: 'wired',
    routes: ['/director/players/[playerId]'],
    safetyNotes: [
      'Output sanitized via buildParentSupportGuidanceDraft + sanitizeParentFacingText.',
      'Raw coach notes NEVER included in parent-facing output.',
      'Draft is director-only until approved.',
      'Send path not yet built — draft creation is safe.',
    ],
    missingDependencies: ['Parent send mechanism (future sprint)'],
  },

  {
    id: 'draft_player_summary',
    displayName: 'Draft a player development brief',
    naturalLanguageExamples: [
      'Write a player brief',
      'Summarize what this player needs to work on',
      'Draft a development note for this player',
    ],
    domain: 'player_summaries',
    actionClass: 'draft_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['PlayerContext'],
    requiredObjectIds: ['player_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'player_brief',
    implementationStatus: 'implemented_and_wired',
    uiWiringStatus: 'wired',
    routes: ['/director/players/[playerId]'],
    safetyNotes: ['Director-only draft. Not player-visible until approved and explicitly exposed.'],
    missingDependencies: [],
  },

  {
    id: 'draft_curriculum_item',
    displayName: 'Draft a new curriculum content item',
    naturalLanguageExamples: [
      'Draft a curriculum item for this level',
      'Create a lesson for Orange 2',
      'Add a new activity to the curriculum',
    ],
    domain: 'curriculum',
    actionClass: 'draft_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['CurriculumContext'],
    requiredObjectIds: ['level_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'curriculum_adjustment',
    implementationStatus: 'implemented_not_wired',
    uiWiringStatus: 'not_wired',
    routes: ['/director/curriculum', '/director/curriculum/builder'],
    safetyNotes: ['Routes through proposed_actions. No direct curriculum_content_items write.'],
    missingDependencies: ['DONNA curriculum draft entry point on /director/curriculum'],
  },

  {
    id: 'draft_curriculum_mission',
    displayName: 'Draft a new player mission',
    naturalLanguageExamples: [
      'Create a mission for this level',
      'Draft a player challenge',
      'Add a new mission to the curriculum',
    ],
    domain: 'missions',
    actionClass: 'draft_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['CurriculumContext'],
    requiredObjectIds: ['level_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'curriculum_adjustment',
    implementationStatus: 'registry_only',
    uiWiringStatus: 'not_wired',
    routes: ['/director/curriculum', '/director/players/[playerId]'],
    safetyNotes: ['Mission model exists in src/lib/player/missionModel.ts. Draft action path not yet built.'],
    missingDependencies: ['Mission draft server action', 'Mission draft UI entry point'],
  },

  {
    id: 'draft_curriculum_badge',
    displayName: 'Draft a new curriculum badge',
    naturalLanguageExamples: [
      'Create a badge for this achievement',
      'Draft a new badge',
      'Add a badge for completing Orange 2',
    ],
    domain: 'badges',
    actionClass: 'draft_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['CurriculumContext'],
    requiredObjectIds: ['level_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'curriculum_adjustment',
    implementationStatus: 'registry_only',
    uiWiringStatus: 'not_wired',
    routes: ['/director/curriculum'],
    safetyNotes: ['Badge model exists in src/lib/badges/badgeModel.ts. Draft action path not yet built.'],
    missingDependencies: ['Badge draft server action', 'Badge draft UI entry point'],
  },

  {
    id: 'draft_drill',
    displayName: 'Draft a new training drill',
    naturalLanguageExamples: [
      'Create a drill for score awareness',
      'Draft a new drill for emotional resets',
      'Build me a drill for kids struggling with footwork',
      'Design a Green 2 drill for 10-and-under players',
      'Build me a Green 2 session for kids struggling with score awareness and emotional resets',
    ],
    domain: 'curriculum',
    actionClass: 'draft_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['CurriculumContext'],
    requiredObjectIds: [],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'curriculum_adjustment',
    implementationStatus: 'registry_only',
    uiWiringStatus: 'not_wired',
    routes: ['/director/curriculum', '/director/curriculum/builder'],
    safetyNotes: [
      'Complex multi-part requests (level + skill + age + emotional context) are treated as ambiguous until intent is confirmed.',
      'DONNA drafts drill content for director review — never writes to curriculum_drills until approved.',
    ],
    missingDependencies: ['Drill draft server action', 'Drill draft UI on /director/curriculum'],
  },

  {
    id: 'draft_video_metadata',
    displayName: 'Draft video or media metadata',
    naturalLanguageExamples: [
      'Add metadata to this video',
      'Tag this clip for coach cues',
      'Draft a video description',
      'Link this video to the curriculum',
    ],
    domain: 'media_video',
    actionClass: 'draft_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['CurriculumContext'],
    requiredObjectIds: ['media_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'curriculum_adjustment',
    implementationStatus: 'registry_only',
    uiWiringStatus: 'not_wired',
    routes: ['/director/curriculum', '/director/templates'],
    safetyNotes: ['Video visibility changes are a separate action (propose_video_visibility_change).'],
    missingDependencies: ['Media/video backend model', 'Video metadata draft server action'],
  },

  {
    id: 'draft_assessment_recommendation',
    displayName: 'Draft an assessment recommendation for a player',
    naturalLanguageExamples: [
      'Recommend an assessment for this player',
      'Draft what the next assessment should focus on',
      'Suggest assessment areas for this player',
    ],
    domain: 'assessments',
    actionClass: 'draft_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['PlayerContext'],
    requiredObjectIds: ['player_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'player_brief',
    implementationStatus: 'partially_implemented',
    uiWiringStatus: 'partial',
    routes: ['/director/players/[playerId]'],
    safetyNotes: [
      'donnaDirectorIntelligenceActions.ts has related draft paths.',
      'Specific assessment recommendation proposed_action shape not yet fully defined.',
    ],
    missingDependencies: ['Assessment recommendation proposed_action type definition'],
  },

  {
    id: 'route_coach_note_to_review',
    displayName: 'Route a coach observation to the review queue',
    naturalLanguageExamples: [
      'Send this observation to the review queue',
      'Flag this coach note for director review',
      'Route this note for approval',
    ],
    domain: 'coach_notes',
    actionClass: 'draft_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['PlayerContext'],
    requiredObjectIds: ['player_id', 'coach_observation_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'player_observation',
    implementationStatus: 'implemented_not_wired',
    uiWiringStatus: 'not_wired',
    routes: ['/director/players/[playerId]', '/director/coaches/[coachId]'],
    safetyNotes: ['Coach notes never reach parent/player portals until approved and visibility explicitly enabled.'],
    missingDependencies: ['Route-to-review UI entry point on player profile and coach profile pages'],
  },

  {
    id: 'draft_session_plan',
    displayName: 'Draft a session plan',
    naturalLanguageExamples: [
      'Build me a session for Green 2',
      'Create a session plan for tomorrow',
      'Draft a 60-minute session for Orange 1',
      'Create a session for kids struggling with score awareness',
    ],
    domain: 'sessions',
    actionClass: 'draft_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['CurriculumContext'],
    requiredObjectIds: [],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'session_wrap_up_v1',
    implementationStatus: 'partially_implemented',
    uiWiringStatus: 'partial',
    routes: ['/director/sessions', '/director/templates'],
    safetyNotes: [
      'Complex requests (level + age + skill + emotional context) are clarified before DONNA drafts.',
      'Fitness template session generation currently bypasses review queue — P1 fix pending (Sprint plan item).',
    ],
    missingDependencies: ['Review gate on fitness template session generation'],
  },

  {
    id: 'draft_coach_brief',
    displayName: 'Draft a coach communication brief',
    naturalLanguageExamples: [
      'Write a message to this coach',
      'Draft a brief for the coach about this player',
      'Create a coaching note for this session',
    ],
    domain: 'coach_portal',
    actionClass: 'draft_only',
    allowedRoles: ['academy_director'],
    requiredContext: ['PlayerContext'],
    requiredObjectIds: ['player_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'coach_communication',
    implementationStatus: 'implemented_and_wired',
    uiWiringStatus: 'wired',
    routes: ['/director/players/[playerId]', '/director/coaches/[coachId]'],
    safetyNotes: ['saveCoachCommunicationDraftAction.ts — draft goes to proposed_actions, not sent until approved.'],
    missingDependencies: [],
  },

  // ── review_required ───────────────────────────────────────────────────────
  // DONNA proposes a significant change. Director must review in review queue.
  // No effect until director takes explicit action.

  {
    id: 'propose_level_movement',
    displayName: 'Propose a level advancement for director review',
    naturalLanguageExamples: [
      'Ask DONNA to draft a level advancement',
      'Propose moving this player up a level',
      'Draft a level movement for review',
      'Start the level advancement review process',
    ],
    domain: 'level_movement',
    actionClass: 'review_required',
    allowedRoles: ['academy_director'],
    requiredContext: ['PlayerContext'],
    requiredObjectIds: ['player_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'level_review',
    implementationStatus: 'implemented_and_wired',
    uiWiringStatus: 'wired',
    routes: ['/director/level-up', '/director/players/[playerId]'],
    safetyNotes: [
      'DONNA creates level_review proposed_action only.',
      'NEVER writes to player_curriculum_states directly.',
      'Director must approve in review queue before any level change.',
      'Apply path (DonnaLevelMovementApplyControls) not yet wired to DonnaDraftCard in review queue.',
    ],
    missingDependencies: ['Wire DonnaLevelMovementApplyControls to DonnaDraftCard in /director/review'],
  },

  {
    id: 'propose_player_placement',
    displayName: 'Propose an initial player level placement',
    naturalLanguageExamples: [
      'Recommend a placement for this new player',
      'Suggest which level this player should be in',
      'Get a placement recommendation based on the interview',
    ],
    domain: 'player_profiles',
    actionClass: 'review_required',
    allowedRoles: ['academy_director'],
    requiredContext: ['PlacementContext'],
    requiredObjectIds: ['player_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'placement',
    implementationStatus: 'implemented_not_wired',
    uiWiringStatus: 'not_wired',
    routes: ['/director/placement'],
    safetyNotes: [
      'placementDraftAction.ts exists — no UI entry point yet.',
      'finalize_player_placement() is the only function that activates a player.',
      'DONNA never activates a player directly.',
    ],
    missingDependencies: ['DONNA placement suggestion button on /director/placement'],
  },

  {
    id: 'recommend_group_adjustment',
    displayName: 'Recommend a group or roster adjustment',
    naturalLanguageExamples: [
      'Should we move any players between groups?',
      'Who would benefit from being in a different group?',
      'Recommend a roster change',
    ],
    domain: 'groups_rosters',
    actionClass: 'review_required',
    allowedRoles: ['academy_director'],
    requiredContext: ['AcademyContext'],
    requiredObjectIds: [],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'move_player_group',
    implementationStatus: 'registry_only',
    uiWiringStatus: 'not_wired',
    routes: ['/director/players', '/director/signals'],
    safetyNotes: ['DONNA never mutates the roster directly. All group changes go through proposed_actions.'],
    missingDependencies: ['Group adjustment server action', 'move_player_group proposed_action type'],
  },

  {
    id: 'propose_badge_award',
    displayName: 'Propose awarding a badge to a player',
    naturalLanguageExamples: [
      'Award this player the consistency badge',
      'Propose a badge for this achievement',
      'Suggest a badge award for this player',
    ],
    domain: 'badges',
    actionClass: 'review_required',
    allowedRoles: ['academy_director'],
    requiredContext: ['PlayerContext'],
    requiredObjectIds: ['player_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'badge_award',
    implementationStatus: 'registry_only',
    uiWiringStatus: 'not_wired',
    routes: ['/director/players/[playerId]'],
    safetyNotes: [
      'Badge model exists in src/lib/badges/badgeModel.ts.',
      'badgeEligibilityEngine.ts exists.',
      'badge_award proposed_action type not yet defined.',
    ],
    missingDependencies: [
      'badge_award proposed_action type',
      'Badge award server action',
      'Badge award UI entry point on /director/players/[playerId]',
    ],
  },

  {
    id: 'propose_video_visibility_change',
    displayName: 'Propose changing who can see a video or media item',
    naturalLanguageExamples: [
      'Make this video visible to players',
      'Allow parents to see this clip',
      'Hide this video from the player portal',
      'Change who can see this media',
    ],
    domain: 'media_video',
    actionClass: 'review_required',
    allowedRoles: ['academy_director'],
    requiredContext: ['CurriculumContext'],
    requiredObjectIds: ['media_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: true,
    auditLogRequired: true,
    proposedActionType: 'curriculum_adjustment',
    implementationStatus: 'registry_only',
    uiWiringStatus: 'not_wired',
    routes: ['/director/curriculum', '/director/players/[playerId]'],
    safetyNotes: [
      'Any change that makes content visible to parents or players requires director approval.',
      'visibilityControls.ts (src/lib/player/) exists — video visibility writes not yet built.',
    ],
    missingDependencies: ['Video visibility proposed_action type', 'Media visibility server action'],
  },

  {
    id: 'propose_curriculum_licensing_review',
    displayName: 'Propose a curriculum licensing review',
    naturalLanguageExamples: [
      'Flag this for licensing review',
      'Propose a licensing check for this content',
      'Request a curriculum licensing audit',
    ],
    domain: 'licensing_health',
    actionClass: 'review_required',
    allowedRoles: ['academy_director'],
    requiredContext: ['CurriculumContext'],
    requiredObjectIds: [],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: 'curriculum_adjustment',
    implementationStatus: 'registry_only',
    uiWiringStatus: 'not_wired',
    routes: ['/director/curriculum', '/director/kpi'],
    safetyNotes: ['No licensing changes occur — DONNA flags for director attention only.'],
    missingDependencies: [
      'Licensing health backend model',
      'Curriculum licensing review proposed_action type',
    ],
  },

  // ── director_approval_required ────────────────────────────────────────────
  // Director must take explicit action. DONNA facilitates but never decides.

  {
    id: 'approve_review_item',
    displayName: 'Approve a review queue item',
    naturalLanguageExamples: [
      'Approve this',
      'Mark this as approved',
      'I approve this level movement draft',
      'Approve this parent summary',
    ],
    domain: 'review_queue',
    actionClass: 'director_approval_required',
    allowedRoles: ['academy_director'],
    requiredContext: ['ReviewItemContext'],
    requiredObjectIds: ['proposed_action_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: null,
    implementationStatus: 'implemented_and_wired',
    uiWiringStatus: 'wired',
    routes: ['/director/review', '/director/review/[actionId]'],
    safetyNotes: [
      'Approval sets proposed_actions.status = approved.',
      'Execution is a separate step — approval alone does not apply changes.',
      'execute_approved_action() or a module-specific apply action must be called after approval.',
    ],
    missingDependencies: [],
  },

  {
    id: 'reject_review_item',
    displayName: 'Reject a review queue item',
    naturalLanguageExamples: [
      'Reject this',
      'Do not approve this',
      'Reject this draft',
      'This is not right — reject it',
    ],
    domain: 'review_queue',
    actionClass: 'director_approval_required',
    allowedRoles: ['academy_director'],
    requiredContext: ['ReviewItemContext'],
    requiredObjectIds: ['proposed_action_id'],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: null,
    implementationStatus: 'implemented_and_wired',
    uiWiringStatus: 'wired',
    routes: ['/director/review', '/director/review/[actionId]'],
    safetyNotes: ['Rejection sets proposed_actions.status = rejected. No downstream mutation.'],
    missingDependencies: [],
  },

  // ── platform_owner_required ───────────────────────────────────────────────
  // Requires platform-owner authorization. Beyond director scope.

  {
    id: 'override_global_knowledge_visibility',
    displayName: 'Override global knowledge library visibility',
    naturalLanguageExamples: [
      'Make this global knowledge item public',
      'Change who can see this curriculum resource across all academies',
      'Override the visibility on this shared resource',
    ],
    domain: 'global_knowledge',
    actionClass: 'platform_owner_required',
    allowedRoles: [],
    requiredContext: ['GlobalKnowledgeContext'],
    requiredObjectIds: ['knowledge_item_id'],
    requiredApprovalLevel: 'platform_owner',
    parentPlayerVisibilityRisk: true,
    auditLogRequired: true,
    proposedActionType: null,
    implementationStatus: 'blocked_by_permissions',
    uiWiringStatus: 'not_wired',
    routes: [],
    safetyNotes: [
      'Global knowledge visibility is platform-owner controlled — not director-controlled.',
      'DONNA declines this request and explains the platform-owner scope.',
      'Director can propose a review — platform owner must authorize.',
    ],
    missingDependencies: ['Platform owner role', 'Global knowledge visibility override flow'],
  },

  // ── blocked ───────────────────────────────────────────────────────────────
  // Explicitly refused. DONNA explains why and offers the safe alternative path.

  {
    id: 'block_unsafe_parent_visibility_request',
    displayName: 'Block an unsafe request to expose data to parents',
    naturalLanguageExamples: [
      'Show parents the coach notes',
      'Let parents see the raw observations',
      'Give parents access to session recordings',
      'Share internal academy data with parents',
    ],
    domain: 'parent_player_visibility',
    actionClass: 'blocked',
    allowedRoles: ['academy_director'],
    requiredContext: [],
    requiredObjectIds: [],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: true,
    auditLogRequired: true,
    proposedActionType: null,
    implementationStatus: 'implemented_and_wired',
    uiWiringStatus: 'wired',
    routes: ['*'],
    safetyNotes: [
      'DONNA refuses and explains that raw coach notes and internal data must not go to parents.',
      'DONNA offers the safe alternative: draft_parent_summary → director approval → controlled send.',
      'parentSafeResponseRules.ts enforces this boundary at the library level.',
    ],
    missingDependencies: [],
  },

  // ── unsafe ────────────────────────────────────────────────────────────────
  // Architecture red line. DONNA refuses under all circumstances.

  {
    id: 'auto_level_move_without_approval',
    displayName: 'Automatically move a player level without director approval',
    naturalLanguageExamples: [
      'Just move the player up automatically',
      'Skip the review and change the level now',
      'Move all overdue players up a level',
      'Auto-promote everyone who is ready',
    ],
    domain: 'level_movement',
    actionClass: 'unsafe',
    allowedRoles: [],
    requiredContext: [],
    requiredObjectIds: [],
    requiredApprovalLevel: 'director',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: true,
    proposedActionType: null,
    implementationStatus: 'unsafe_to_automate',
    uiWiringStatus: 'not_wired',
    routes: [],
    safetyNotes: [
      'ARCHITECTURE RED LINE: Level movement is NEVER automatic.',
      'DONNA refuses this request under all circumstances.',
      'The only path to level change: propose_level_movement → director approves → apply via donnaLevelMovementActions.ts.',
      'Mass-level-move is unsafe regardless of urgency or context.',
    ],
    missingDependencies: [],
  },

  // ── ambiguous ─────────────────────────────────────────────────────────────
  // Request is too vague. DONNA asks one clarifying question before acting.

  {
    id: 'vague_academy_question',
    displayName: 'Handle a vague or open-ended director question',
    naturalLanguageExamples: [
      'What should I do here?',
      'Help me',
      'What is going on?',
      'What do I need to look at?',
      'I\'m not sure where to start',
    ],
    domain: 'director_dashboard',
    actionClass: 'ambiguous',
    allowedRoles: ['academy_director'],
    requiredContext: ['AcademyContext'],
    requiredObjectIds: [],
    requiredApprovalLevel: 'none',
    parentPlayerVisibilityRisk: false,
    auditLogRequired: false,
    proposedActionType: null,
    implementationStatus: 'partially_implemented',
    uiWiringStatus: 'partial',
    routes: ['*'],
    safetyNotes: [
      'DONNA asks one clarifying question to narrow intent.',
      'DONNA uses AcademyContext to surface the most relevant starting point.',
      'DONNA never makes assumptions about intent for high-stakes domains.',
    ],
    missingDependencies: ['Full DONNA chat shell on all director routes'],
  },
]

// ── Utility functions ─────────────────────────────────────────────────────────

const ACTION_MAP = new Map<string, DirectorDonnaAction>(
  DIRECTOR_DONNA_ACTIONS.map(a => [a.id, a]),
)

export function getDirectorDonnaActionById(id: string): DirectorDonnaAction | undefined {
  return ACTION_MAP.get(id)
}

export function getDirectorDonnaActionsByRoute(route: string): DirectorDonnaAction[] {
  return DIRECTOR_DONNA_ACTIONS.filter(
    a => a.routes.includes('*') || a.routes.includes(route),
  )
}

export function getDirectorDonnaActionsByDomain(
  domain: DirectorActionDomain,
): DirectorDonnaAction[] {
  return DIRECTOR_DONNA_ACTIONS.filter(a => a.domain === domain)
}

export function getDirectorDonnaActionsByClass(
  actionClass: DirectorActionClass,
): DirectorDonnaAction[] {
  return DIRECTOR_DONNA_ACTIONS.filter(a => a.actionClass === actionClass)
}
