// Sprint 2891–2920 — DONNA Knowledge Promotion Engine V1
// Part 2 — Promotion Candidate Model
//
// A KnowledgePromotionCandidate is a LearningEntry that has been nominated
// for promotion into official DONNA knowledge. It carries forward the evidence,
// scoring, and context from the Learning Ledger plus draft knowledge content.
//
// Status machine:
//   candidate → in_review → approved → promoted
//                         ↘ rejected  (terminal — learning still preserved in ledger)
//   approved → archived   (if superseded by newer knowledge)
//   promoted → archived   (if withdrawn)
//
// Design rules:
//   - Pure TypeScript. No DB, no API, no React, no side effects.
//   - Candidates are read-only derivations of LearningEntries.
//   - Approval/rejection decisions always require a named approver.
//   - OpenAI drafts are advisory — marked isDraft, requiresApproval.

import type { LearningEntry, LearningTopicDomain } from '../learning/learningEntryModel'
import type { AcademyOSConcept } from '../conversation/donnaMeaningExtractor'

// ── Candidate status ──────────────────────────────────────────────────────────

export type CandidateStatus =
  | 'candidate'    // nominated from an approved LearningEntry
  | 'in_review'    // surfaced in director review queue
  | 'approved'     // director or owner approved the draft
  | 'rejected'     // director or owner rejected — not promoted
  | 'promoted'     // approved + written to ApprovedKnowledgeRegistry
  | 'archived'     // superseded, withdrawn, or obsolete

// ── Knowledge target scope ────────────────────────────────────────────────────

export type KnowledgeTargetScope =
  | 'academy_specific_knowledge'      // applies to this academy only
  | 'global_platform_knowledge_candidate'  // nominated for cross-academy use (platform owner review)
  | 'brian_philosophy_knowledge'      // academy owner's philosophy
  | 'curriculum_knowledge'            // informs curriculum decisions
  | 'coach_standard_knowledge'        // coaching execution standards
  | 'parent_communication_knowledge'  // parent messaging norms
  | 'operating_model_knowledge'       // how the academy operates

// ── Promotion candidate ───────────────────────────────────────────────────────

export interface KnowledgePromotionCandidate {
  id: string
  learningEntryId: string             // source LearningEntry
  academyId: string

  // Derived from learning entry
  sourceSummary: string               // verbatim from LearningEntry.summary
  sourceEvidence: string[]            // verbatim from LearningEntry.examplePhrases + evidence
  concepts: AcademyOSConcept[]
  topicDomain: LearningTopicDomain
  sourceReliability: number           // 0–1 from source reliability engine
  learningScore: number               // 0–100 composite score

  // Draft knowledge (generated by DonnaKnowledgeDraftGenerator)
  proposedTitle: string               // suggested title — director may edit
  proposedBody: string                // suggested knowledge body — director may edit
  targetScope: KnowledgeTargetScope
  isDraft: boolean                    // true until director finalizes
  draftGeneratedBy: 'system' | 'openai'

  // Scoring
  promotionScore: number              // 0–100 — how strongly this should be promoted

  // Approval gates
  requiresOwnerApproval: boolean      // for global scope or brian_philosophy
  requiresBrianApproval: boolean      // for brian_direct sourced learning

  // Status
  status: CandidateStatus
  createdAt: string
  reviewedAt: string | null
  approvedBy: string | null
  approvedAt: string | null
  rejectedReason: string | null

  // Contradiction flag
  hasContradict: boolean
  contradictEntryIds: string[]        // IDs of contradicting entries

  // Metadata
  metadata: Record<string, unknown>
}

// ── Status transitions ────────────────────────────────────────────────────────

export const CANDIDATE_STATUS_TRANSITIONS: Record<CandidateStatus, CandidateStatus[]> = {
  candidate:  ['in_review', 'rejected', 'archived'],
  in_review:  ['approved', 'rejected', 'candidate'],  // can send back to candidate with edits
  approved:   ['promoted', 'archived'],
  rejected:   ['archived'],
  promoted:   ['archived'],
  archived:   [],
}

export function canTransitionCandidate(from: CandidateStatus, to: CandidateStatus): boolean {
  return CANDIDATE_STATUS_TRANSITIONS[from].includes(to)
}

// ── Promotion score ───────────────────────────────────────────────────────────
// Promotion score is derived from the learning score + source factors.
// Higher than learning score for high-reliability, high-frequency Brian learnings.

export function computePromotionScore(entry: LearningEntry): number {
  let base = entry.learningScore

  // Brian direct gets a 10-point boost
  if (entry.sourceType === 'brian_direct') base += 10

  // High frequency patterns get a boost (up to 5 points)
  const frequencyBoost = Math.min(entry.frequency / 10 * 5, 5)
  base += frequencyBoost

  // High source reliability gets a boost (up to 5 points)
  const reliabilityBoost = entry.sourceReliability >= 0.90 ? 5
    : entry.sourceReliability >= 0.80 ? 3
    : 0
  base += reliabilityBoost

  return Math.min(Math.round(base), 100)
}

// ── Target scope inference ────────────────────────────────────────────────────

export function inferTargetScope(entry: LearningEntry): KnowledgeTargetScope {
  if (entry.sourceType === 'brian_direct') return 'brian_philosophy_knowledge'

  const domainScopeMap: Partial<Record<LearningTopicDomain, KnowledgeTargetScope>> = {
    curriculum:            'curriculum_knowledge',
    player_development:    'curriculum_knowledge',
    coaching_philosophy:   'brian_philosophy_knowledge',
    group_management:      'coach_standard_knowledge',
    session_execution:     'coach_standard_knowledge',
    parent_relations:      'parent_communication_knowledge',
    academy_operations:    'operating_model_knowledge',
    enrollment:            'operating_model_knowledge',
    competitive_readiness: 'curriculum_knowledge',
    player_psychology:     'curriculum_knowledge',
  }

  return domainScopeMap[entry.topicDomain] ?? 'academy_specific_knowledge'
}

// ── Factory ───────────────────────────────────────────────────────────────────

let _counter = 0

export function generateCandidateId(): string {
  _counter += 1
  return `kpc-${Date.now()}-${_counter}`
}

export function createCandidate(
  entry: LearningEntry,
  draft: { proposedTitle: string; proposedBody: string; draftGeneratedBy: 'system' | 'openai' },
): KnowledgePromotionCandidate {
  const targetScope = inferTargetScope(entry)
  const promotionScore = computePromotionScore(entry)

  return {
    id: generateCandidateId(),
    learningEntryId: entry.id,
    academyId: entry.academyId,

    sourceSummary: entry.summary,
    sourceEvidence: [entry.evidence, ...entry.examplePhrases].filter(Boolean),
    concepts: entry.concepts,
    topicDomain: entry.topicDomain,
    sourceReliability: entry.sourceReliability,
    learningScore: entry.learningScore,

    proposedTitle: draft.proposedTitle,
    proposedBody: draft.proposedBody,
    targetScope,
    isDraft: true,
    draftGeneratedBy: draft.draftGeneratedBy,

    promotionScore,

    requiresOwnerApproval: (
      targetScope === 'global_platform_knowledge_candidate' ||
      targetScope === 'brian_philosophy_knowledge'
    ),
    requiresBrianApproval: entry.sourceType === 'brian_direct',

    status: 'candidate',
    createdAt: new Date().toISOString(),
    reviewedAt: null,
    approvedBy: null,
    approvedAt: null,
    rejectedReason: null,

    hasContradict: false,
    contradictEntryIds: [],

    metadata: {
      originalSourceType: entry.sourceType,
      originalRole: entry.role,
    },
  }
}
