// Sprint 987 — DONNA Human Approval Bridge V1
// The bridge between DONNA draft proposals and the proposed_actions review pipeline.
// Pure TypeScript for types + helpers — actual server action write is in the API layer.
//
// Purpose:
//   When DONNA wants to draft an action for director review, the approval bridge:
//   1. Validates the draft (is it safe? is it complete? is it appropriately scoped?)
//   2. Formats the draft as a proposed_action payload
//   3. Returns a validated draft payload the server action can safely write
//   4. Never writes directly — the server action in /api or _actions handles the DB write
//
// Safety contract:
//   - Bridge returns a DraftApprovalPayload — caller must pass to server action
//   - Director must see the draft and explicitly confirm before server action runs
//   - No draft bypasses the review queue
//   - No auto-approve, no auto-reject

// ── Draft input ───────────────────────────────────────────────────────────────

export type DraftActionType =
  | 'coach_observation'       // Coach observes player behavior — goes to review
  | 'session_note'            // Director note about a session
  | 'parent_update_draft'     // Parent-safe update — must be approved before send
  | 'curriculum_adjustment'   // Curriculum change proposal
  | 'attendance_exception'    // Attendance exception flag
  | 'level_readiness_signal'  // Signal that player may be ready to advance

export interface DraftApprovalInput {
  /** Type of action being drafted */
  actionType: DraftActionType
  /** Academy ID — required for RLS scoping */
  academyId: string
  /** Actor (director or coach) profile ID */
  actorId: string
  /** Structured content for this draft — must not contain raw private data */
  content: Record<string, unknown>
  /** Human-readable rationale DONNA provides for this draft */
  rationale: string
  /** Whether this draft contains any player-facing content */
  isPlayerFacing: boolean
  /** Whether this draft contains any parent-facing content */
  isParentFacing: boolean
}

// ── Validated draft payload ───────────────────────────────────────────────────

export interface DraftApprovalPayload {
  /** Validated action type */
  action_type: DraftActionType
  /** Academy ID for RLS */
  academy_id: string
  /** Actor profile ID */
  created_by: string
  /** Structured payload — validated and sanitized */
  payload: Record<string, unknown>
  /** DONNA's rationale for this draft */
  rationale: string
  /** Status: always 'pending_review' — never auto-approved */
  status: 'pending_review'
  /** Visibility flags */
  is_player_facing: boolean
  /** Whether parent-safe review is required */
  is_parent_facing: boolean
  /** Whether this draft was generated by DONNA (for audit purposes) */
  generated_by_donna: boolean
  /** Validation summary */
  validationSummary: string
}

// ── Validation result ─────────────────────────────────────────────────────────

export interface DraftValidationResult {
  valid: boolean
  errors: string[]
  warnings: string[]
}

// ── Blocked content patterns ──────────────────────────────────────────────────

const BLOCKED_CONTENT_PATTERNS = [
  /\bsocial security\b/i,
  /\bpassword\b/i,
  /\bcredit card\b/i,
  /\bdate of birth\b/i,
  /\bmedical\b/i,
  /\bdiagnos/i,
  /\braw.*note/i,
]

function containsBlockedContent(content: Record<string, unknown>): boolean {
  const str = JSON.stringify(content)
  return BLOCKED_CONTENT_PATTERNS.some(p => p.test(str))
}

// ── Draft validator ───────────────────────────────────────────────────────────

const VALID_ACTION_TYPES: DraftActionType[] = [
  'coach_observation', 'session_note', 'parent_update_draft',
  'curriculum_adjustment', 'attendance_exception', 'level_readiness_signal',
]

/**
 * Validate a draft approval input before building the payload.
 * Returns errors that must be resolved before the draft can be submitted.
 */
export function validateDraftInput(input: DraftApprovalInput): DraftValidationResult {
  const errors: string[] = []
  const warnings: string[] = []

  if (!VALID_ACTION_TYPES.includes(input.actionType)) {
    errors.push(`Unknown action type: '${input.actionType}'`)
  }
  if (!input.academyId || input.academyId.length < 10) {
    errors.push('Invalid academyId — must be a valid UUID')
  }
  if (!input.actorId || input.actorId.length < 10) {
    errors.push('Invalid actorId — must be a valid UUID')
  }
  if (!input.rationale || input.rationale.trim().length < 10) {
    errors.push('Rationale is required and must be at least 10 characters')
  }
  if (containsBlockedContent(input.content)) {
    errors.push('Draft content contains blocked sensitive data patterns. Remove sensitive information before submitting.')
  }
  if (input.isParentFacing) {
    warnings.push('This draft is parent-facing. Ensure content is parent-safe before approving.')
  }
  if (input.isPlayerFacing) {
    warnings.push('This draft is player-facing. Ensure content is appropriate for player visibility before approving.')
  }

  return { valid: errors.length === 0, errors, warnings }
}

// ── Payload builder ───────────────────────────────────────────────────────────

/**
 * Build a validated DraftApprovalPayload from input.
 * Returns null when validation fails — caller must handle and show errors.
 * The payload can be passed to the server action for the actual DB write.
 * Director must see and confirm the payload before the server action runs.
 */
export function buildDraftApprovalPayload(
  input: DraftApprovalInput,
): { payload: DraftApprovalPayload; validation: DraftValidationResult } | { payload: null; validation: DraftValidationResult } {
  const validation = validateDraftInput(input)

  if (!validation.valid) {
    return { payload: null, validation }
  }

  const payload: DraftApprovalPayload = {
    action_type: input.actionType,
    academy_id: input.academyId,
    created_by: input.actorId,
    payload: input.content,
    rationale: input.rationale.slice(0, 500),
    status: 'pending_review',
    is_player_facing: input.isPlayerFacing,
    is_parent_facing: input.isParentFacing,
    generated_by_donna: true,
    validationSummary: validation.warnings.length > 0
      ? `Valid. Warnings: ${validation.warnings.join('; ')}`
      : 'Valid. No warnings.',
  }

  return { payload, validation }
}

// ── Director confirmation prompt ──────────────────────────────────────────────

/**
 * Generate the confirmation prompt DONNA shows the director before submitting a draft.
 * The director must read this and click "Submit to Review Queue" to proceed.
 */
export function buildConfirmationPrompt(payload: DraftApprovalPayload): string {
  const lines = [
    `DONNA has prepared a **${payload.action_type.replace(/_/g, ' ')}** draft for your review.`,
    '',
    `**Rationale:** ${payload.rationale}`,
    '',
    payload.is_parent_facing ? '⚠ This draft is parent-facing. Please review carefully before approving.' : '',
    payload.is_player_facing ? '⚠ This draft is player-facing. Please confirm content is appropriate.' : '',
    '',
    '**This draft will be submitted to your Review Queue.** Nothing is applied until you explicitly approve it there. You can reject or modify it at any time.',
    '',
    'Click **Submit to Review Queue** to proceed, or **Cancel** to discard.',
  ].filter(line => line !== undefined)

  return lines.join('\n').trim()
}
