// DONNA Action Contract — Mega Sprint 1991–2020
// Single standard for all executable DONNA actions.
// No page-specific implementations. No duplicate approval systems.
//
// Execution model (V1):
//   DONNA drafts → Director reviews in-context → Director navigates to action route
//   V2: Add voice_commands insert to unlock direct proposed_actions writes.

import type { DonnaActionTarget, ActionTargetEntityType } from '../operations/academyChangeEngine'

export type { DonnaActionTarget, ActionTargetEntityType }

// ── Action identity ───────────────────────────────────────────────────────────

export type DonnaActionId =
  | 'open_player'
  | 'open_curriculum'
  | 'open_approval'
  | 'create_coach_note'
  | 'create_player_note'
  | 'schedule_reassessment'
  | 'draft_parent_message'
  | 'create_session_draft'
  | 'review_advancement'
  | 'review_curriculum_recommendation'

export type DonnaActionEntityType = ActionTargetEntityType

export type DonnaActionExecutionType =
  | 'navigation'       // opens a route — no DB write
  | 'proposed_action'  // creates a proposed_actions record (V2)

export type DonnaActionStatus =
  | 'draft'            // generated by DONNA, not yet seen by director
  | 'pending'          // director has seen it, hasn't acted
  | 'in_progress'      // director is working on it
  | 'completed'        // director acted
  | 'dismissed'        // director dismissed without acting
  | 'expired'          // draft expired before director acted

export type DonnaActionSourceEngine =
  | 'operating_partner'
  | 'decision_engine'
  | 'evolution_engine'
  | 'attention_engine'
  | 'curriculum_engine'
  | 'manual'

// ── Action definition (registry entry) ───────────────────────────────────────
// Immutable definition of what a DONNA action IS.
// Does not contain entity-specific data.

export interface DonnaAction {
  id:                  DonnaActionId
  label:               string
  description:         string
  entityType:          DonnaActionEntityType
  requiredPermission:  'academy_director' | 'head_coach' | 'coach'
  approvalRequired:    boolean
  executionType:       DonnaActionExecutionType
  baseRoute:           string   // template: '/director/players/{entityId}'
}

// ── Action draft ──────────────────────────────────────────────────────────────
// A specific instance of a DonnaAction, bound to an entity.
// Created by donnaDraftBuilder. Carries a DonnaActionTarget for routing.

export interface DonnaActionDraft {
  id:              string    // 'draft_<timestamp>_<random6>'
  actionId:        DonnaActionId
  label:           string    // "Schedule reassessment for 3 players"
  description:     string    // human-readable reason
  entityId:        string | null
  entityLabel:     string | null
  entityType:      DonnaActionEntityType
  actionTarget:    DonnaActionTarget  // where to take the director
  proposedPayload: Record<string, unknown>
  approvalRequired: boolean
  sourceEngine:    DonnaActionSourceEngine
  sourceSignal:    string    // what triggered this draft
  domain:          string    // 'players' | 'curriculum' | 'coaches' | 'parents' | 'system'
  status:          DonnaActionStatus
  createdAt:       string
}

// ── Action result ─────────────────────────────────────────────────────────────

export interface DonnaActionResult {
  ok:          boolean
  message:     string
  draftId:     string
  executedAt:  string | null
  route:       string | null
}

// ── Action approval record ────────────────────────────────────────────────────

export interface DonnaActionApproval {
  draftId:    string
  approvedBy: string
  approvedAt: string
  note:       string | null
}

// ── Work queue aggregate ──────────────────────────────────────────────────────
// Summary of pending drafts by domain — used by DonnaWorkQueue component.

export interface DonnaWorkQueueSummary {
  totalPending:   number
  byDomain: Array<{
    domain:       string
    count:        number
    route:        string
    topDraftLabel: string
  }>
  generatedAt:    string
}

// ── ID factory ────────────────────────────────────────────────────────────────

export function newDraftId(): string {
  const ts  = Date.now().toString(36)
  const rnd = Math.random().toString(36).slice(2, 8)
  return `draft_${ts}_${rnd}`
}
