-- ============================================================
-- ACADEMY OS — MIGRATION 021: RECOMMENDATIONS
-- player_recommendations, session_recommendations
--
-- Loop position:
--   ← player_priorities (020) — what to work on
--   ← decision_scores (019)   — how urgent
--   ← player_phase_states (017) — what's allowed now
--   ← player_load_aggregation (018) — fatigue constraints
--   → sessions (recommended sessions must reference this)
--   → exercises (session recs filter exercises by priority tags)
--   → player_outcomes (016) — did following the rec improve outcomes?
--   → learning system (022) — were recs accepted or overridden?
--
-- player_recommendations: strategic-level (what to focus on this week/cycle)
-- session_recommendations: tactical-level (specific sessions + exercises to run)
-- ============================================================

-- ============================================================
-- PLAYER RECOMMENDATIONS
-- Strategic development recommendations for a player.
-- One recommendation per priority cycle (typically weekly).
-- Generated by generate_player_recommendations().
-- ============================================================
CREATE TYPE recommendation_status AS ENUM (
  'pending_review',   -- generated, awaiting director/head review
  'approved',         -- accepted as-is
  'modified',         -- accepted with changes
  'overridden',       -- completely replaced by human decision
  'rejected',         -- not acting on this
  'in_progress',      -- sessions being executed to fulfill this rec
  'completed',        -- outcome recorded, loop closed
  'expired'           -- never acted on within expiry window
);

CREATE TABLE player_recommendations (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  academy_id      UUID NOT NULL REFERENCES academies(id) ON DELETE CASCADE,
  player_id       UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,

  -- Source references (the full loop)
  priority_id     UUID REFERENCES player_priorities(id),
  decision_score_id UUID REFERENCES decision_scores(id),

  -- What is recommended
  title           TEXT NOT NULL,
  description     TEXT,
  recommendation_type TEXT NOT NULL CHECK (recommendation_type IN (
    'schedule_session',       -- create specific session(s)
    'increase_competition',   -- enter more tournaments
    'reduce_load',            -- drop session frequency/intensity
    'schedule_reassessment',  -- formal evaluation needed
    'move_group',             -- player ready for different group
    'change_track',           -- switch development track
    'add_constraint',         -- injury/load management needed
    'coach_attention'         -- flag for manual coach review
  )),

  -- Specifics
  recommended_track           development_track,
  recommended_group_id        UUID REFERENCES groups(id),
  target_sessions_per_week    INTEGER,
  target_intensity_range      JSONB,  -- {"min": 2, "max": 4}
  target_block_types          block_type[],
  target_exercise_tags        TEXT[],
  suggested_reassessment_date DATE,

  -- Confidence and urgency
  confidence_score  NUMERIC(4,3) NOT NULL CHECK (confidence_score BETWEEN 0 AND 1),
  urgency           TEXT NOT NULL DEFAULT 'routine'
                    CHECK (urgency IN ('immediate', 'urgent', 'high', 'routine', 'monitor')),
  priority_level    TEXT NOT NULL DEFAULT 'medium'
                    CHECK (priority_level IN ('critical', 'high', 'medium', 'low')),

  -- Review and approval
  status            recommendation_status NOT NULL DEFAULT 'pending_review',
  reviewed_by       UUID REFERENCES profiles(id),
  reviewed_at       TIMESTAMPTZ,
  reviewer_notes    TEXT,

  -- Override (populated if status = 'modified' or 'overridden')
  override_recommendation_type TEXT,
  override_notes    TEXT,
  overridden_by     UUID REFERENCES profiles(id),
  overridden_at     TIMESTAMPTZ,

  -- Outcome link (populated when the recommendation is completed)
  outcome_ids       UUID[],   -- player_outcomes that fulfilled this
  outcome_notes     TEXT,
  completed_at      TIMESTAMPTZ,

  expires_at        TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '14 days'),
  generated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_recs_player    ON player_recommendations(player_id, status, generated_at DESC);
CREATE INDEX idx_recs_academy   ON player_recommendations(academy_id, status, urgency);
CREATE INDEX idx_recs_pending   ON player_recommendations(academy_id, expires_at)
  WHERE status = 'pending_review';

CREATE TRIGGER tr_recommendations_updated_at
  BEFORE UPDATE ON player_recommendations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- SESSION RECOMMENDATIONS
-- Tactical-level: specific sessions to run to fulfil a player_recommendation.
-- Links the strategic recommendation to concrete template + exercises.
-- ============================================================
CREATE TABLE session_recommendations (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  academy_id      UUID NOT NULL REFERENCES academies(id) ON DELETE CASCADE,
  player_id       UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  recommendation_id UUID NOT NULL REFERENCES player_recommendations(id) ON DELETE CASCADE,

  -- What to run
  title           TEXT NOT NULL,
  session_type    TEXT NOT NULL CHECK (session_type IN (
    'skill_focus', 'competition_prep', 'recovery', 'assessment', 'full_training', 'match_play'
  )),
  suggested_template_id UUID REFERENCES templates(id),
  target_date     DATE,
  target_duration_min INTEGER,
  target_intensity INTEGER CHECK (target_intensity BETWEEN 1 AND 5),

  -- Block and exercise focus (integration with exercises table)
  focus_block_types   block_type[],
  focus_exercise_ids  UUID[],     -- specific exercises to include
  focus_exercise_tags TEXT[],     -- filter exercises by tags if no specific IDs

  -- Rationale
  rationale       TEXT,
  coaching_cues   TEXT[],   -- what the coach should focus on during this session

  -- Priority link (why this session matters)
  priority_id     UUID REFERENCES player_priorities(id),
  signal_ids      UUID[],   -- signals this session is designed to address

  -- Execution status
  status          TEXT NOT NULL DEFAULT 'suggested'
                  CHECK (status IN ('suggested', 'scheduled', 'completed', 'skipped')),
  executed_session_id UUID REFERENCES sessions(id),  -- session created from this rec
  outcome_id          UUID REFERENCES player_outcomes(id),

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_session_recs_player ON session_recommendations(player_id, status, target_date);
CREATE INDEX idx_session_recs_rec    ON session_recommendations(recommendation_id);

CREATE TRIGGER tr_session_recs_updated_at
  BEFORE UPDATE ON session_recommendations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- Back-reference FK: player_priorities.linked_recommendation_id
-- ============================================================
ALTER TABLE player_priorities
  ADD CONSTRAINT fk_priorities_recommendation
  FOREIGN KEY (linked_recommendation_id)
  REFERENCES player_recommendations(id);

-- ============================================================
-- Back-reference FK: player_outcomes.recommendation_id
-- ============================================================
ALTER TABLE player_outcomes
  ADD CONSTRAINT fk_outcomes_recommendation
  FOREIGN KEY (recommendation_id)
  REFERENCES player_recommendations(id);

-- ============================================================
-- GENERATE_PLAYER_RECOMMENDATIONS()
-- Creates player_recommendations and session_recommendations
-- from the current priorities + decision score.
-- Called after generate_player_priorities() or on demand.
-- ============================================================
CREATE OR REPLACE FUNCTION generate_player_recommendations(
  p_player_id  UUID,
  p_academy_id UUID,
  p_reviewer_required BOOLEAN DEFAULT true
)
RETURNS JSONB AS $$
DECLARE
  v_score     decision_scores%ROWTYPE;
  v_phase     player_phase;
  v_load      player_load_aggregation%ROWTYPE;
  v_priority  player_priorities%ROWTYPE;
  v_rec_id    UUID;
  v_srec_id   UUID;
  v_recs_created INTEGER := 0;
  v_srecs_created INTEGER := 0;
  v_template  templates%ROWTYPE;
BEGIN
  SELECT * INTO v_score FROM decision_scores WHERE player_id = p_player_id;
  v_phase := get_player_phase(p_player_id);
  SELECT * INTO v_load  FROM player_load_aggregation WHERE player_id = p_player_id;

  -- Generate a recommendation per active priority (top 3 only)
  FOR v_priority IN
    SELECT * FROM player_priorities
    WHERE player_id = p_player_id
    AND is_active = true
    AND status = 'open'
    ORDER BY priority_rank
    LIMIT 3
  LOOP
    -- Determine recommendation type from priority category
    INSERT INTO player_recommendations (
      academy_id, player_id,
      priority_id, decision_score_id,
      title, description, recommendation_type,
      target_sessions_per_week,
      target_intensity_range,
      target_block_types, target_exercise_tags,
      confidence_score, urgency, priority_level,
      status, expires_at
    ) VALUES (
      p_academy_id, p_player_id,
      v_priority.id, v_score.id,

      CASE v_priority.category
        WHEN 'technical_skill'      THEN 'Focus sessions: ' || v_priority.title
        WHEN 'competition_exposure' THEN 'Competition plan: ' || v_priority.title
        WHEN 'load_management'      THEN 'Load reduction required: ' || v_priority.title
        WHEN 'reassessment'         THEN 'Schedule assessment: ' || v_priority.title
        WHEN 'promotion_readiness'  THEN 'Promotion evaluation: ' || v_priority.title
        ELSE v_priority.title
      END,

      v_priority.description,

      CASE v_priority.category
        WHEN 'technical_skill'      THEN 'schedule_session'
        WHEN 'tactical_skill'       THEN 'schedule_session'
        WHEN 'physical_fitness'     THEN 'schedule_session'
        WHEN 'competition_exposure' THEN 'increase_competition'
        WHEN 'load_management'      THEN 'reduce_load'
        WHEN 'reassessment'         THEN 'schedule_reassessment'
        WHEN 'promotion_readiness'  THEN 'move_group'
        ELSE 'coach_attention'
      END::TEXT,

      CASE v_priority.category
        WHEN 'load_management' THEN 2  -- reduce sessions
        ELSE 3
      END,

      CASE v_priority.category
        WHEN 'load_management' THEN '{"min": 1, "max": 2}'::JSONB
        WHEN 'competition_exposure' THEN '{"min": 3, "max": 4}'::JSONB
        ELSE '{"min": 2, "max": 4}'::JSONB
      END,

      v_priority.suggested_block_types,
      v_priority.suggested_exercise_tags,

      v_priority.confidence_score,
      v_priority.urgency,
      v_priority.priority_level,

      CASE WHEN p_reviewer_required THEN 'pending_review' ELSE 'approved' END::recommendation_status,
      NOW() + INTERVAL '14 days'
    ) RETURNING id INTO v_rec_id;

    -- Update priority with back-reference
    UPDATE player_priorities SET linked_recommendation_id = v_rec_id WHERE id = v_priority.id;

    -- Generate a session recommendation for schedule_session types
    IF v_priority.category IN ('technical_skill', 'tactical_skill', 'physical_fitness') THEN
      -- Find a matching template if possible
      SELECT t.* INTO v_template
      FROM templates t
      WHERE t.academy_id = p_academy_id
      AND (
        v_priority.suggested_exercise_tags IS NULL
        OR t.tags && v_priority.suggested_exercise_tags
      )
      AND t.is_active = true
      ORDER BY t.is_default DESC, t.created_at DESC
      LIMIT 1;

      INSERT INTO session_recommendations (
        academy_id, player_id, recommendation_id,
        title, session_type,
        suggested_template_id,
        target_date, target_duration_min, target_intensity,
        focus_block_types, focus_exercise_tags,
        rationale, priority_id, signal_ids, status
      ) VALUES (
        p_academy_id, p_player_id, v_rec_id,
        'Session: ' || v_priority.title,
        CASE v_priority.category
          WHEN 'technical_skill'  THEN 'skill_focus'
          WHEN 'tactical_skill'   THEN 'competition_prep'
          WHEN 'physical_fitness' THEN 'full_training'
          ELSE 'skill_focus'
        END,
        v_template.id,
        CURRENT_DATE + 3,  -- suggest 3 days out
        90,
        CASE v_phase
          WHEN 'competition'     THEN 3
          WHEN 'pre_competition' THEN 4
          WHEN 'recovery'        THEN 2
          ELSE 4
        END,
        v_priority.suggested_block_types,
        v_priority.suggested_exercise_tags,
        v_priority.description,
        v_priority.id,
        v_priority.source_signal_ids,
        'suggested'
      ) RETURNING id INTO v_srec_id;

      v_srecs_created := v_srecs_created + 1;
    END IF;

    v_recs_created := v_recs_created + 1;
  END LOOP;

  RETURN jsonb_build_object(
    'success', true,
    'player_id', p_player_id,
    'recommendations_created', v_recs_created,
    'session_recommendations_created', v_srecs_created,
    'urgency', v_score.urgency
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- RUN_FULL_ENGINE()
-- End-to-end: score → priorities → recommendations for one player.
-- The canonical entry point after any signal or outcome.
-- ============================================================
CREATE OR REPLACE FUNCTION run_full_engine(
  p_player_id  UUID,
  p_academy_id UUID
)
RETURNS JSONB AS $$
DECLARE
  v_score_id  UUID;
  v_priority_count INTEGER;
  v_rec_result JSONB;
BEGIN
  v_score_id       := score_player(p_player_id, p_academy_id);
  v_priority_count := generate_player_priorities(p_player_id, p_academy_id);
  v_rec_result     := generate_player_recommendations(p_player_id, p_academy_id);

  RETURN jsonb_build_object(
    'success', true,
    'player_id', p_player_id,
    'score_id', v_score_id,
    'priorities_generated', v_priority_count,
    'recommendations', v_rec_result
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- RLS
-- ============================================================
ALTER TABLE player_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE session_recommendations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Staff see player recommendations"   ON player_recommendations FOR SELECT USING (academy_id = auth_academy_id() AND auth_is_staff());
CREATE POLICY "Directors review recommendations"   ON player_recommendations FOR UPDATE USING (academy_id = auth_academy_id() AND auth_is_director_or_head());
CREATE POLICY "System creates recommendations"     ON player_recommendations FOR INSERT WITH CHECK (academy_id = auth_academy_id());

CREATE POLICY "Staff see session recommendations"  ON session_recommendations FOR SELECT USING (academy_id = auth_academy_id() AND auth_is_staff());
CREATE POLICY "Staff manage session recommendations" ON session_recommendations FOR ALL USING (academy_id = auth_academy_id() AND auth_is_staff());
