-- ============================================================
-- ACADEMY OS — MIGRATION 029: COACHING OUTPUT LAYER
-- coaching_messages: structured messages connecting recommendations
-- and signals to specific communication for players and coaches.
--
-- Loop integration:
--   ← player_recommendations (021) — message context
--   ← player_development_signals (014) — signal driving the message
--   ← player_behavior_profiles (027) — tone selection
--   ← player_predictions (028) — prediction context in coach message
--   → sessions (007) — message can be linked to a session
--   → coach → player communication pipeline
--
-- Design: messages are generated by the engine with structured
-- content. Coaches can edit before sending. The sent/unsent flag
-- ensures no message is delivered without review.
-- ============================================================

CREATE TYPE message_tone AS ENUM (
  'encouragement',   -- positive reinforcement
  'challenge',       -- push harder, raise the bar
  'correction',      -- address a technical or behavioral issue
  'informational',   -- neutral update, schedule, logistics
  'concern'          -- flag a risk to player/parent
);

CREATE TYPE message_audience AS ENUM (
  'player',          -- displayed/sent to player
  'coach',           -- internal coaching note
  'parent',          -- parent/guardian update
  'all'              -- relevant to all parties
);

CREATE TABLE coaching_messages (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  academy_id            UUID NOT NULL REFERENCES academies(id) ON DELETE CASCADE,
  player_id             UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,

  -- Source linkage
  recommendation_id     UUID REFERENCES player_recommendations(id) ON DELETE SET NULL,
  signal_id             UUID REFERENCES player_development_signals(id) ON DELETE SET NULL,
  session_id            UUID REFERENCES sessions(id) ON DELETE SET NULL,

  -- Message content
  -- Short: ≤280 chars, player-facing
  short_message         TEXT NOT NULL,
  -- Detailed: coach-facing, includes reasoning, signal context, suggested actions
  detailed_message      TEXT NOT NULL,

  -- Coaching metadata
  coaching_focus        TEXT,
  -- e.g., "UTR regression recovery", "reassessment preparation", "load management"

  tone                  message_tone NOT NULL DEFAULT 'informational',
  audience              message_audience NOT NULL DEFAULT 'coach',

  -- Generation source
  generated_by          TEXT NOT NULL DEFAULT 'system'
                        CHECK (generated_by IN ('system', 'coach')),

  -- Delivery state
  is_reviewed           BOOLEAN NOT NULL DEFAULT false,
  reviewed_by           UUID REFERENCES profiles(id),
  reviewed_at           TIMESTAMPTZ,

  is_sent               BOOLEAN NOT NULL DEFAULT false,
  sent_by               UUID REFERENCES profiles(id),
  sent_at               TIMESTAMPTZ,

  -- Coach edits to system-generated content
  edited_short_message  TEXT,
  edited_detailed_message TEXT,

  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_coaching_messages_player     ON coaching_messages(player_id, created_at DESC);
CREATE INDEX idx_coaching_messages_rec        ON coaching_messages(recommendation_id);
CREATE INDEX idx_coaching_messages_unsent     ON coaching_messages(academy_id, is_sent, is_reviewed) WHERE is_sent = false;
CREATE INDEX idx_coaching_messages_signal     ON coaching_messages(signal_id);

CREATE TRIGGER tr_coaching_messages_updated_at
  BEFORE UPDATE ON coaching_messages
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- GENERATE_COACHING_MESSAGE()
-- Creates a structured coaching message from a recommendation.
-- Pulls from: recommendation, reasoning, behavioral profile,
-- signal context, and latest prediction.
-- ============================================================
CREATE OR REPLACE FUNCTION generate_coaching_message(
  p_recommendation_id UUID
)
RETURNS UUID AS $$
DECLARE
  v_rec       player_recommendations%ROWTYPE;
  v_reasoning recommendation_reasoning%ROWTYPE;
  v_behavior  player_behavior_profiles%ROWTYPE;
  v_signal    player_development_signals%ROWTYPE;
  v_pred      player_predictions%ROWTYPE;
  v_tone      message_tone;
  v_short     TEXT;
  v_detailed  TEXT;
  v_focus     TEXT;
  v_audience  message_audience;
  v_id        UUID;
BEGIN
  SELECT * INTO v_rec     FROM player_recommendations WHERE id = p_recommendation_id;
  IF NOT FOUND THEN RETURN NULL; END IF;

  SELECT * INTO v_reasoning FROM recommendation_reasoning  WHERE recommendation_id = p_recommendation_id;
  SELECT * INTO v_behavior  FROM player_behavior_profiles  WHERE player_id = v_rec.player_id;

  -- Get primary driving signal
  IF v_rec.priority_id IS NOT NULL THEN
    SELECT s.* INTO v_signal
    FROM player_development_signals s
    JOIN player_priorities pri ON pri.primary_signal_id = s.id
    WHERE pri.id = v_rec.priority_id
    LIMIT 1;
  END IF;

  -- Get latest prediction
  SELECT * INTO v_pred
  FROM player_predictions
  WHERE player_id = v_rec.player_id
  ORDER BY generated_at DESC
  LIMIT 1;

  -- ── TONE SELECTION ────────────────────────────────────────
  -- Tone is determined by signal type + urgency + behavioral profile
  v_tone := CASE
    -- Load/injury signals → concern
    WHEN v_rec.recommendation_type = 'reduce_load' THEN 'concern'
    -- Positive progress → encouragement
    WHEN v_signal.signal_type IN ('utr_improvement', 'score_improvement', 'promotion_ready') THEN 'encouragement'
    -- Regressions → correction (for high pressure-tolerance) or concern (for low)
    WHEN v_signal.signal_type IN ('utr_regression', 'score_regression') THEN
      CASE WHEN COALESCE(v_behavior.pressure_tolerance, 0.5) >= 0.6 THEN 'correction' ELSE 'concern' END
    -- Overdue assessment → informational
    WHEN v_signal.signal_type = 'reassessment_overdue' THEN 'informational'
    -- Urgency drives challenge tone for match-motivated players
    WHEN v_rec.urgency IN ('immediate', 'urgent') AND
         COALESCE(v_behavior.competition_response, 'neutral') = 'match_motivated' THEN 'challenge'
    ELSE 'informational'
  END;

  -- ── AUDIENCE ──────────────────────────────────────────────
  v_audience := CASE
    WHEN v_rec.recommendation_type = 'reduce_load' THEN 'all'  -- parents should know
    WHEN v_tone = 'concern' THEN 'all'
    ELSE 'coach'
  END;

  -- ── COACHING FOCUS ────────────────────────────────────────
  v_focus := CASE v_rec.recommendation_type
    WHEN 'schedule_session'      THEN 'Technical development — ' || COALESCE(v_rec.title, 'skill session')
    WHEN 'increase_competition'  THEN 'Competitive exposure — match volume'
    WHEN 'reduce_load'           THEN 'Load management — injury prevention'
    WHEN 'schedule_reassessment' THEN 'Formal assessment — progress check'
    WHEN 'move_group'            THEN 'Group transition — level alignment'
    ELSE v_rec.recommendation_type
  END;

  -- ── SHORT MESSAGE (≤280 chars, player-facing) ─────────────
  v_short := CASE v_tone
    WHEN 'encouragement' THEN
      'Great progress! ' ||
      COALESCE(v_signal.title, 'Your recent performance shows improvement') ||
      '. Keep it up — next focus: ' || v_focus || '.'
    WHEN 'challenge' THEN
      'Time to raise the bar. ' ||
      COALESCE(v_signal.title, 'Your data shows room to grow') ||
      '. Coach has scheduled: ' || COALESCE(v_rec.title, v_focus) || '.'
    WHEN 'correction' THEN
      'Let''s address this together. ' ||
      COALESCE(v_signal.title, 'A focus area needs attention') ||
      '. Recommended: ' || COALESCE(v_rec.title, v_focus) || '.'
    WHEN 'concern' THEN
      'Your wellbeing comes first. ' ||
      COALESCE(v_signal.title, 'Load/health flags detected') ||
      '. We''re adjusting your program: ' || COALESCE(v_rec.title, v_focus) || '.'
    ELSE
      COALESCE(v_rec.title, v_focus) || '. ' ||
      COALESCE(v_signal.title, 'Review your latest development data') || '.'
  END;

  -- Truncate to 280 chars
  IF length(v_short) > 280 THEN
    v_short := left(v_short, 277) || '...';
  END IF;

  -- ── DETAILED MESSAGE (coach-facing) ───────────────────────
  v_detailed :=
    '=== COACHING NOTE: ' || UPPER(v_rec.recommendation_type) || ' ===' || E'\n\n' ||

    'PLAYER: ' || v_rec.player_id || E'\n' ||
    'RECOMMENDATION: ' || COALESCE(v_rec.title, 'N/A') || E'\n' ||
    'URGENCY: ' || v_rec.urgency || ' | CONFIDENCE: ' || ROUND(COALESCE(v_rec.confidence_score, 0) * 100) || '%' || E'\n\n' ||

    'SIGNAL CONTEXT:' || E'\n' ||
    COALESCE('  Primary: ' || v_signal.title || ' (' || v_signal.severity || ', conf: ' ||
      ROUND(v_signal.confidence * 100) || '%)' || E'\n', '  No primary signal.' || E'\n') ||

    E'\n' || 'ENGINE REASONING:' || E'\n' ||
    '  ' || COALESCE(v_reasoning.explanation_text, 'No reasoning record available.') || E'\n\n';

  -- Add prediction context if available
  IF v_pred IS NOT NULL THEN
    v_detailed := v_detailed ||
      'PREDICTION (30-day):' || E'\n' ||
      '  Performance: ' || COALESCE(v_pred.predicted_performance_score::TEXT, '?') || '/10' || E'\n' ||
      '  Injury risk: ' || v_pred.injury_risk_label || ' (' || ROUND(v_pred.injury_risk_score * 100) || '%)' || E'\n' ||
      '  Readiness: ' || v_pred.readiness_label || E'\n' ||
      '  Confidence: ' || ROUND(v_pred.prediction_confidence * 100) || '%' || E'\n\n';
  END IF;

  -- Add behavioral context
  v_detailed := v_detailed ||
    'BEHAVIORAL PROFILE:' || E'\n' ||
    '  Volume response: ' || COALESCE(v_behavior.volume_response, 'unknown') || E'\n' ||
    '  Fatigue sensitivity: ' || ROUND(COALESCE(v_behavior.fatigue_sensitivity, 0.5) * 100) || '%' || E'\n' ||
    '  Competition response: ' || COALESCE(v_behavior.competition_response, 'neutral') || E'\n' ||
    '  Preferred learning: ' || COALESCE(v_behavior.learning_preference, 'drill_heavy') || E'\n' ||
    '  Load adjustment: ' || COALESCE(v_behavior.load_adjustment_factor::TEXT, '1.0') || E'\n\n' ||

    'COACHING APPROACH:' || E'\n' ||
    '  Tone: ' || v_tone::TEXT || E'\n' ||
    '  Deliver as: ' || COALESCE(v_behavior.learning_preference, 'drill_heavy') || E'\n' ||
    CASE v_behavior.learning_preference
      WHEN 'game_based'     THEN '  Use match scenarios and game formats to deliver this focus.' || E'\n'
      WHEN 'drill_heavy'    THEN '  Use structured, blocked drills with clear repetition targets.' || E'\n'
      WHEN 'video_analysis' THEN '  Prepare video clips showing this pattern before the session.' || E'\n'
      WHEN 'verbal_cues'    THEN '  Use short, sharp verbal cues; minimize lengthy technical explanations.' || E'\n'
      ELSE '' END ||

    E'\n' || '---' || E'\n' ||
    'Generated by Academy OS engine at ' || TO_CHAR(NOW(), 'YYYY-MM-DD HH24:MI') || ' UTC';

  INSERT INTO coaching_messages (
    academy_id, player_id,
    recommendation_id, signal_id,
    short_message, detailed_message,
    coaching_focus, tone, audience,
    generated_by
  ) VALUES (
    v_rec.academy_id, v_rec.player_id,
    p_recommendation_id, v_signal.id,
    v_short, v_detailed,
    v_focus, v_tone, v_audience,
    'system'
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- Update RUN_FULL_ENGINE() — final version with all 5 layers.
-- ============================================================
CREATE OR REPLACE FUNCTION run_full_engine(
  p_player_id  UUID,
  p_academy_id UUID
)
RETURNS JSONB AS $$
DECLARE
  v_score_id         UUID;
  v_priority_count   INTEGER;
  v_rec_result       JSONB;
  v_rec              player_recommendations%ROWTYPE;
  v_srec             session_recommendations%ROWTYPE;
  v_reasoning_count  INTEGER := 0;
  v_exercise_count   INTEGER := 0;
  v_prediction_id    UUID;
  v_message_count    INTEGER := 0;
  v_rec_ids          UUID[] := '{}';
BEGIN
  -- 1. Score (behavioral model applied inside score_player)
  v_score_id := score_player(p_player_id, p_academy_id);

  -- 2. Generate priorities from signals
  v_priority_count := generate_player_priorities(p_player_id, p_academy_id);

  -- 3. Generate recommendations from priorities
  v_rec_result := generate_player_recommendations(p_player_id, p_academy_id);

  -- 4. For each new recommendation: reasoning + exercises + coaching message
  FOR v_rec IN
    SELECT * FROM player_recommendations
    WHERE player_id = p_player_id
    AND status = 'pending_review'
    AND generated_at > NOW() - INTERVAL '1 minute'
  LOOP
    PERFORM build_recommendation_reasoning(v_rec.id);
    v_reasoning_count := v_reasoning_count + 1;
    v_rec_ids := array_append(v_rec_ids, v_rec.id);

    FOR v_srec IN
      SELECT * FROM session_recommendations WHERE recommendation_id = v_rec.id
    LOOP
      v_exercise_count := v_exercise_count + COALESCE(
        populate_session_rec_exercises(v_srec.id), 0
      );
    END LOOP;
  END LOOP;

  -- 5. Generate predictions (back-populates predicted_score_impact on reasoning)
  v_prediction_id := generate_player_predictions(p_player_id, p_academy_id, 30);

  -- 6. Generate coaching messages (after predictions are available)
  FOR v_rec IN
    SELECT * FROM player_recommendations
    WHERE player_id = p_player_id
    AND status = 'pending_review'
    AND generated_at > NOW() - INTERVAL '1 minute'
  LOOP
    PERFORM generate_coaching_message(v_rec.id);
    v_message_count := v_message_count + 1;
  END LOOP;

  -- 7. Log the decision cycle
  PERFORM log_decision_cycle(p_player_id, p_academy_id, v_score_id, v_rec_ids);

  RETURN jsonb_build_object(
    'success', true,
    'player_id', p_player_id,
    'score_id', v_score_id,
    'priorities_generated', v_priority_count,
    'recommendations', v_rec_result,
    'reasoning_built', v_reasoning_count,
    'exercises_populated', v_exercise_count,
    'prediction_id', v_prediction_id,
    'messages_generated', v_message_count
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- View: v_coaching_messages_pending
-- Unsent messages with player name and recommendation context.
-- ============================================================
CREATE OR REPLACE VIEW v_coaching_messages_pending AS
SELECT
  cm.id,
  cm.academy_id,
  cm.player_id,
  pl.first_name,
  pl.last_name,
  cm.recommendation_id,
  cm.tone,
  cm.audience,
  cm.coaching_focus,
  cm.short_message,
  cm.detailed_message,
  cm.edited_short_message,
  cm.is_reviewed,
  cm.created_at,
  pr.urgency           AS recommendation_urgency,
  pr.recommendation_type
FROM coaching_messages cm
JOIN players pl ON pl.id = cm.player_id
LEFT JOIN player_recommendations pr ON pr.id = cm.recommendation_id
WHERE cm.is_sent = false
ORDER BY
  CASE pr.urgency
    WHEN 'immediate' THEN 1
    WHEN 'urgent'    THEN 2
    WHEN 'high'      THEN 3
    WHEN 'routine'   THEN 4
    ELSE 5
  END,
  cm.created_at DESC;

-- ============================================================
-- RLS
-- ============================================================
ALTER TABLE coaching_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Staff see coaching messages"      ON coaching_messages FOR SELECT USING (academy_id = auth_academy_id() AND auth_is_staff());
CREATE POLICY "Staff manage coaching messages"   ON coaching_messages FOR ALL   USING (academy_id = auth_academy_id() AND auth_is_staff());
CREATE POLICY "System creates coaching messages" ON coaching_messages FOR INSERT WITH CHECK (academy_id = auth_academy_id());
